{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ContainersTournament",
    "query": "discord-bot, competition-core, session-controller, social, bracket-controller, auth, account-linking"
   },
   {
    "name": "ContainersMonalog",
    "query": "filebeat, grafana, elasticsearch"
   }
  ]
 },
 "panels": [
  {
   "title": "${ContainersTournament} log count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "ContainersTournament",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container.name=${ContainersTournament}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tournament logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "container.name:${ContainersTournament}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Monalog logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "container.name:${ContainersMonalog}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Other logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "NOT container.name:${ContainersMonalog} AND NOT container.name:${ContainersTournament}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}