-- rollback fuzis:5
DROP TRIGGER STATUS_UPDATE_TRIGGER ON BOOKS.BOOK_READING_STATUS;
DROP FUNCTION BOOKS.STATUS_UPDATE_FUNCTION;
DROP INDEX BOOKS.BOOK_INDEX;
DROP INDEX ACCOUNTS.USER_INDEX;
DROP INDEX BOOKS.COLLECTION_INDEX;
DROP INDEX BOOKS.BOOK_AUTHORS_INDEX;

-- rollback fuzis:4
DROP TABLE BOOKS.LIKED_COLLECTIONS;
DROP TABLE BOOKS.COLLECTION_VIEW_PRIVILEGES;
DROP TABLE BOOKS.BOOKS_BOOK_COLLECTIONS;
DROP TABLE BOOKS.BOOK_COLLECTIONS;
DROP TABLE BOOKS.BOOK_READING_STATUS;
DROP TABLE BOOKS.READING_GOALS;
DROP TABLE BOOKS.BOOK_REVIEWS;
DROP TABLE BOOKS.BOOKS_GENRES;
DROP TABLE BOOKS.BOOKS_AUTHORS;
DROP TABLE BOOKS.BOOKS;
DROP TABLE BOOKS.AUTHORS;
DROP TABLE BOOKS.GENRES;
DROP TABLE BOOKS.SUBSCRIBERS;
DROP TYPE BOOKS.GOALS_TYPE;
DROP TYPE BOOKS.CVP_STATUS;
DROP TYPE BOOKS.COLLECTION_TYPE;
DROP TYPE BOOKS.CONFIDENTIALITY;
DROP TYPE BOOKS.READING_STATUS;
DROP TYPE BOOKS.GOALS_PERIODS;

-- rollback fuzis:3
DROP TABLE ACCOUNTS.USER_PROFILES;
DROP TYPE ACCOUNTS.USER_STATUS;

-- rollback fuzis:2
DROP TABLE IMAGES.IMAGE_LINKS;
DROP TABLE IMAGES.IMAGE_DATAS;

-- rollback fuzis:1
DROP SCHEMA BOOKS;
DROP SCHEMA IMAGES;