package com.fuzis.integrationbus.route;

import com.fuzis.integrationbus.exception.AuthenticationException;
import com.fuzis.integrationbus.exception.ServiceFall;
import org.apache.camel.Exchange;
import org.apache.camel.LoggingLevel;
import org.apache.camel.builder.RouteBuilder;
import org.springframework.stereotype.Component;

@Component
public class BookAdminRoutes extends RouteBuilder {
    @Override
    public void configure() {
        errorHandler(defaultErrorHandler()
                .maximumRedeliveries(0)
                .retryAttemptedLogLevel(LoggingLevel.WARN));

        from("platform-http:/oapi/v1/collections/books/admin?httpMethodRestrict=GET")
                .routeId("user-books-collections-books-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/admin/collections/${header.collectionId}/books"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collections/admin?httpMethodRestrict=GET")
                .routeId("user-books-collection-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/admin/collections/${header.collectionId}"))
                .to("direct:sd-call-finalize");


        from("platform-http:/oapi/v1/collection/admin?httpMethodRestrict=PUT")
                .routeId("user-books-collection-put-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collection/admin?httpMethodRestrict=DELETE")
                .routeId("user-books-collection-delete-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collection/book/admin?httpMethodRestrict=POST")
                .routeId("user-books-collection-book-post-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}/books"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collection/book/admin?httpMethodRestrict=DELETE")
                .routeId("user-books-collection-book-delete-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId,bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}/books/${header.bookId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collection/privilege/admin?httpMethodRestrict=POST")
                .routeId("user-books-collection-privileges-post-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}/privileges"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collection/privilege/admin?httpMethodRestrict=DELETE")
                .routeId("user-books-collection-privileges-delete-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId,userId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}/privileges/${header.userId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collection/book/admin?httpMethodRestrict=GET")
                .routeId("user-books-collection-book-get-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId,bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}/books/${header.bookId}/exists"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collection/privilege/admin?httpMethodRestrict=GET")
                .routeId("user-books-collection-privileges-get-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}/privileges"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book/reviews/admin?httpMethodRestrict=PUT")
                .routeId("user-books-book-put-review-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId,X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-Change-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}/reviews"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book/reviews/admin?httpMethodRestrict=DELETE")
                .routeId("user-books-book-delete-review-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId,X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-Change-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}/reviews"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book/admin?httpMethodRestrict=PUT")
                .routeId("user-books-book-put-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("-1"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book/admin?httpMethodRestrict=DELETE")
                .routeId("user-books-book-delete-admin-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("-1"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}"))
                .to("direct:sd-call-finalize");


        from("platform-http:/oapi/v1/author?httpMethodRestrict=POST")
                .routeId("user-books-book-post-author-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/authors"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/author?httpMethodRestrict=DELETE")
                .routeId("user-books-book-delete-author-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("authorId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/authors/${header.authorId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/author?httpMethodRestrict=PUT")
                .routeId("user-books-book-put-author-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("authorId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/authors/${header.authorId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/genre?httpMethodRestrict=PUT")
                .routeId("user-books-book-put-genre-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("genreId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/genres/${header.genreId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/genre?httpMethodRestrict=DELETE")
                .routeId("user-books-book-delete-genre-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("genreId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/genres/${header.genreId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/genre?httpMethodRestrict=POST")
                .routeId("user-books-book-post-genre-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Roles-Required", constant("manage-books"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/genres"))
                .to("direct:sd-call-finalize");


    }
}
